exclude = [
    'https://fonts.gstatic.com/',
    'https://fonts.googleapis.com/',
    'http://go/github',
    'http://go/github-googlecloudplatform',
    'https://medium.com/',
    'https://x.com/',
    'http://localhost:12000/',
    'http://localhost:10020/',
]
exclude_path = [
    ".github/actions/spelling",
    "CHANGELOG.md",
    "docs/partners.md",
    "docs/robots.txt",
    "docs/llms.txt",
    "docs/spec-json.md",
    "docs/spec-proto.md",
    "docs/sdk/python.md",
]

accept = ["200..=299", 403, 408, 429]

max_retries = 0
skip_missing = true
