name: Lint Code Base

on:
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      statuses: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: GitHub Super Linter
        uses: super-linter/super-linter/slim@v8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHELLCHECK_OPTS: -e SC1091 -e 2086
          VALIDATE_ALL_CODEBASE: false
          FILTER_REGEX_EXCLUDE: "^(\\.github/|\\.vscode/).*|CODE_OF_CONDUCT.md|CHANGELOG.md|GOVERNANCE.md|MAINTAINERS.md"
          VALIDATE_BASH: true
          VALIDATE_BASH_EXEC: true
          VALIDATE_CSS: true
          VALIDATE_EDITORCONFIG: true
          VALIDATE_GIT_MERGE_CONFLICT_MARKERS: true
          VALIDATE_GITHUB_ACTIONS: true
          VALIDATE_GITLEAKS: true
          VALIDATE_JSCPD: true
          VALIDATE_JSON: true
          VALIDATE_MARKDOWN: true
          VALIDATE_PROTOBUF: true
          VALIDATE_PYTHON_RUFF: true
          VALIDATE_SHELL_SHFMT: true
          VALIDATE_TOML: true
          VALIDATE_TYPESCRIPT_ES: true
          VALIDATE_YAML: true
          TYPESCRIPT_ES_CONFIG_FILE: ".eslintrc.js"
          MARKDOWN_CONFIG_FILE: ".markdownlint.json"
          PROTOBUF_CONFIG_FILE: ".protolint.yaml"
